    page 60, 132
TITLE   SKELETON (EXE)   ASM skeleton
STACKSG SEGMENT PARA    STACK   'Stack'
    DW  32  DUP (0)
STACKSG ENDS

DATASG  SEGMENT PARA    'Data'
    VAR1    DW  ?
DATASG  ENDS

CODESG  SEGMENT PARA    'Code'
MAIN    PROC    FAR
    ASSUME  SS:STACKSG,DS:DATASG,CS:CODESG
    MOV AX, DATASG
    MOV DS, AX

    MOV AX, 4C00H
    INT 21H
MAIN    ENDP    
CODESG  ENDS
    END MAIN